### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by Ankitm7208** [yusufgngor/iyzico_dart#1]
Access to XMLHttpRequest at 'https://sandbox-api.iyzipay.com/payment/iyzipos/checkoutform/initialize/auth/ecom' from origin 'https://web.trabzononlinemarket.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by yusufgngor** [comment]
Please check out: 
https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code-v0

**Comment by Ankitm7208** [comment]
https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code-v0
Its only working in localhost, not working in live website.

**Comment by yusufgngor** [comment]
Can you install this package locally and add the following code to the IyzipayResource.dart file on line 29?
`headers.addAll({'Access-Control-Allow-Origin': '*'});`

if it works please inform me to update my package. 
if it doesnt work please check your server side configurations.

**Comment by Ankitm7208** [comment]
It didn't work.
