### ISSUE TITLE
3d security

### ISSUE THREAD

**Issue by shahmirzali49** [yusufgngor/iyzico_dart#2]
Merhaba, bu 3d security kodu için attıkta html response dönüyor, bende webviewda gosteriyorum. test karti ile. gelen 3d security kodunuda yaziyorum. submit falan butonuda var. falan bu asamadan sonra nasil yapabilirim ? yani succes mi oldu failure mu oldu ? onu nasil anlaya bilirim? bu datayi nereden almaliyim.

simdiden tesekkurler

**Comment by yusufgngor** [comment]
merhaba, callback url kısmına post ediliyor o bilgiler. Basit bir post page yaparsanız biligleri alıp aynı sayfada bastırabilirsiniz. Ben genelde gelen bilgileri database e atıp daha sora verdiğim id üzerinden çekerek tekrar ulaşıyorum o bilgilere.

**Comment by aea91** [comment]
conversation id ile mi haberleşiyorsunuz db ile callback url e gelenleri almak için. Çünkü payment id dönmüyor sistem
